name: Deploy e Release

# on:
#   workflow_run:
#     workflows: ["Lint with Ruff"]
#     types:
#       - completed

on:
  push:
    tags:
      - '*'


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Checkout bot.sh from repository
        run: |
          git clone --branch v1.0 https://github.com/botcity-dev/cicd-pipeline-utils.git
          chmod +x cicd-pipeline-utils/scripts/bot.sh

      - name: Definir versão da tag
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Deploy Bot
        env:
          SERVER: ${{ secrets.SERVER }}
          LOGIN: ${{ secrets.LOGIN }}
          KEY: ${{ secrets.KEY }}
        run: |
          cicd-pipeline-utils/scripts/bot.sh deploy -version "${{ env.TAG_VERSION }}" -botFile "./bot-login.zip" -botId "bot-demo-cicd" -type "python" -repository "live"

      - name: Release Bot
        env:
          SERVER: ${{ secrets.SERVER }}
          LOGIN: ${{ secrets.LOGIN }}
          KEY: ${{ secrets.KEY }}
        run: |
          cicd-pipeline-utils/scripts/bot.sh release -version "${{ env.TAG_VERSION }}" -botId "bot-demo-cicd"